import React,{useEffect,useState} from "react";
import {ActivityIndicator,Alert,FlatList,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View,Linking} from "react-native";
import {LinearGradient} from "expo-linear-gradient";
import {StatusBar} from "expo-status-bar";
import {colors,radius} from "./src/theme";
import * as api from "./src/api";
import {attachNotificationListeners,registerPushNotifications} from "./src/notifications";
type Tab="home"|"invoices"|"add"|"settings";
type Invoice={id:number;invoice_number:string;customer_name:string;amount:string;paid_amount:string;balance:string;due_date:string;status:string;days_overdue:number;aging_bucket:string};

function Money({value,large=false}:{value:string|number;large?:boolean}){const n=Number(value);return <Text style={[styles.money,large&&styles.moneyLarge]}>₹{isNaN(n)?value:n.toLocaleString("en-IN",{maximumFractionDigits:2})}</Text>}
function Field(p:any){return <View style={{marginBottom:14}}><Text style={styles.label}>{p.label}</Text><TextInput {...p} style={styles.input} placeholderTextColor="#61788B"/></View>}
function Loader(){return <View style={styles.loader}><ActivityIndicator color={colors.cyan}/><Text style={styles.muted}>Loading RecoverFlow…</Text></View>}

function Auth({onDone}:{onDone:()=>void}) {
  const [mode,setMode]=useState<"login"|"register">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[company,setCompany]=useState(""),[loading,setLoading]=useState(false);
  async function submit(){if(!email||password.length<8||(mode==="register"&&!company)){Alert.alert("Check your details","Enter valid account information.");return}setLoading(true);try{if(mode==="login")await api.login(email,password);else await api.register(email,password,company);onDone()}catch(e:any){Alert.alert("Could not continue",e.message)}finally{setLoading(false)}}
  return <SafeAreaView style={styles.auth}><StatusBar style="light"/><LinearGradient colors={["#0E2841","#07111F"]} style={StyleSheet.absoluteFill}/><KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":undefined} style={styles.center}><ScrollView contentContainerStyle={styles.authScroll}>
    <View style={styles.brandRow}><View style={styles.logo}><Text style={styles.logoText}>↗</Text></View><Text style={styles.brand}>RecoverFlow</Text></View>
    <Text style={styles.kicker}>RECEIVABLES OPERATIONS</Text><Text style={styles.hero}>Get paid.{String.fromCharCode(10)}Without the chase.</Text><Text style={styles.authSub}>Invoices, follow-ups and collections in one focused workspace.</Text>
    <View style={styles.card}><View style={styles.segment}><Pressable onPress={()=>setMode("login")} style={[styles.segmentBtn,mode==="login"&&styles.segmentActive]}><Text style={styles.segmentText}>Sign in</Text></Pressable><Pressable onPress={()=>setMode("register")} style={[styles.segmentBtn,mode==="register"&&styles.segmentActive]}><Text style={styles.segmentText}>Create account</Text></Pressable></View>
    {mode==="register"&&<Field label="Company name" value={company} onChangeText={setCompany} placeholder="Your business"/>}<Field label="Email" value={email} onChangeText={setEmail} placeholder="you@company.com" keyboardType="email-address" autoCapitalize="none"/><Field label="Password" value={password} onChangeText={setPassword} placeholder="Minimum 8 characters" secureTextEntry/>
    <Pressable onPress={submit} disabled={loading} style={styles.primary}><Text style={styles.primaryText}>{loading?"Working…":mode==="login"?"Sign in":"Create workspace"}</Text></Pressable></View>
    <Text style={styles.foot}>Secure account access · Shared RecoverFlow backend</Text>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>
}

function Stat({label,value}:{label:string;value:string}){return <View style={styles.stat}><Text style={styles.statLabel}>{label}</Text><Money value={value} large/><Text style={styles.statTone}>Current position</Text></View>}
function Home({onGoInvoices}:{onGoInvoices:()=>void}){
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true);
  useEffect(()=>{api.dashboard().then(setData).catch(()=>{}).finally(()=>setLoading(false))},[]);
  if(loading)return <Loader/>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.kicker}>TODAY</Text><Text style={styles.title}>Collection control center</Text><Text style={styles.muted}>See where cash is stuck and what needs action next.</Text>
    <LinearGradient colors={["#123A58","#0B1728"]} style={styles.heroCard}><Text style={styles.cardKicker}>OUTSTANDING</Text><Money value={data?.outstanding||0} large/><View style={styles.heroRow}><View><Text style={styles.smallMuted}>Overdue</Text><Money value={data?.overdue||0}/></View><View><Text style={styles.smallMuted}>Paid</Text><Money value={data?.paid||0}/></View><View><Text style={styles.smallMuted}>Invoices</Text><Text style={styles.whiteBig}>{data?.invoice_count||0}</Text></View></View></LinearGradient>
    <View style={styles.statsGrid}><Stat label="Due today" value={data?.due_today||"0"}/><Stat label="Customers" value={String(data?.customer_count||0)}/></View>
    <Pressable onPress={onGoInvoices} style={styles.actionCard}><View><Text style={styles.actionTitle}>Open collection queue</Text><Text style={styles.muted}>Review invoices and close the next receivable.</Text></View><Text style={styles.arrow}>→</Text></Pressable>
  </ScrollView>
}
function InvoiceRow({item,onPaid}:{item:Invoice;onPaid:()=>void}){const [busy,setBusy]=useState(false);async function paid(){setBusy(true);try{await api.markPaid(item.id);onPaid()}catch(e:any){Alert.alert("Could not update",e.message)}finally{setBusy(false)}}async function link(){try{const r=await api.createPaymentLink(item.id);await Linking.openURL(r.url)}catch(e:any){Alert.alert("Payment link unavailable",e.message)}}async function whatsapp(){try{await api.sendWhatsapp(item.id);Alert.alert("WhatsApp sent","The reminder was sent through your connected WhatsApp Business account.")}catch(e:any){Alert.alert("WhatsApp unavailable",e.message)}}return <View style={styles.invoice}><View style={styles.invoiceTop}><View style={{flex:1}}><Text style={styles.invoiceCustomer}>{item.customer_name}</Text><Text style={styles.invoiceNo}>{item.invoice_number} · due {item.due_date}</Text></View><Money value={item.balance}/></View><View style={styles.invoiceBottom}><Text style={[styles.badge,item.days_overdue>0&&styles.badgeDanger]}>{item.days_overdue>0?item.days_overdue+"d overdue":item.status}</Text><View style={styles.rowActions}>{item.balance!=="0"&&<><Pressable onPress={link} disabled={busy}><Text style={styles.link}>Pay link</Text></Pressable><Pressable onPress={whatsapp} disabled={busy}><Text style={styles.link}>WhatsApp</Text></Pressable><Pressable onPress={paid} disabled={busy}><Text style={styles.link}>{busy?"Updating…":"Mark paid"}</Text></Pressable></>}</View></View></View>}
function Invoices(){const [items,setItems]=useState<Invoice[]>([]),[loading,setLoading]=useState(true);async function load(){setLoading(true);try{setItems(await api.invoices())}catch{}finally{setLoading(false)}}useEffect(()=>{load()},[]);if(loading)return <Loader/>;return <FlatList data={items} keyExtractor={i=>String(i.id)} style={styles.screen} contentContainerStyle={styles.content} ListHeaderComponent={<View style={{marginBottom:16}}><Text style={styles.kicker}>LEDGER</Text><Text style={styles.title}>Invoices</Text><Text style={styles.muted}>{items.length} receivables in your workspace.</Text></View>} renderItem={({item})=><InvoiceRow item={item} onPaid={load}/>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No invoices yet</Text><Text style={styles.muted}>Add your first receivable from the Add tab.</Text></View>}/>}
function AddInvoice({onDone}:{onDone:()=>void}){const [number,setNumber]=useState(""),[customer,setCustomer]=useState(""),[phone,setPhone]=useState(""),[amount,setAmount]=useState(""),[due,setDue]=useState(new Date().toISOString().slice(0,10)),[gstin,setGstin]=useState(""),[loading,setLoading]=useState(false);async function submit(){if(!number||!customer||!amount){Alert.alert("Missing details","Add invoice number, customer and amount.");return}setLoading(true);try{await api.createInvoice({invoice_number:number,customer_name:customer,phone,amount,paid_amount:"0",issue_date:new Date().toISOString().slice(0,10),due_date:due,gstin});Alert.alert("Invoice created","The receivable is now in your collection queue.");onDone()}catch(e:any){Alert.alert("Could not create invoice",e.message)}finally{setLoading(false)}}return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>NEW RECEIVABLE</Text><Text style={styles.title}>Add invoice</Text><Text style={styles.muted}>Create the receivable that RecoverFlow will track.</Text><View style={styles.card}><Field label="Invoice number" value={number} onChangeText={setNumber} placeholder="INV-2048"/><Field label="Customer" value={customer} onChangeText={setCustomer} placeholder="Customer name"/><Field label="Phone / WhatsApp" value={phone} onChangeText={setPhone} placeholder="919876543210" keyboardType="phone-pad"/><Field label="Amount (INR)" value={amount} onChangeText={setAmount} placeholder="84000" keyboardType="decimal-pad"/><Field label="Due date" value={due} onChangeText={setDue} placeholder="YYYY-MM-DD"/><Field label="Customer GSTIN (optional)" value={gstin} onChangeText={setGstin} placeholder="22AAAAA0000A1Z5" autoCapitalize="characters"/><Pressable onPress={submit} disabled={loading} style={styles.primary}><Text style={styles.primaryText}>{loading?"Creating…":"Create invoice"}</Text></Pressable></View></ScrollView></KeyboardAvoidingView>}
function Settings({onLogout}:{onLogout:()=>void}){const [user,setUser]=useState<any>(null);useEffect(()=>{api.me().then(setUser).catch(()=>{})},[]);return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.kicker}>WORKSPACE</Text><Text style={styles.title}>Settings</Text><View style={styles.card}><Text style={styles.label}>Company</Text><Text style={styles.settingValue}>{user?.company_name||"—"}</Text><Text style={styles.label}>Account</Text><Text style={styles.settingValue}>{user?.email||"—"}</Text><Text style={styles.label}>Plan</Text><Text style={styles.settingValue}>{user?.subscription_plan||"Free / trial"}</Text><Pressable onPress={async()=>{try{const r=await api.testNotification();Alert.alert("Notification test",r.sent?"Test sent to this device.":"No active device token yet. Open the app on a physical device and allow notifications.")}catch(e:any){Alert.alert("Notification test failed",e.message)}}} style={styles.secondaryBtn}><Text style={styles.secondaryText}>Test push notifications</Text></Pressable></View><Pressable onPress={async()=>{await api.logout();onLogout()}} style={styles.dangerBtn}><Text style={styles.dangerText}>Sign out</Text></Pressable></ScrollView>}
export default function App(){
  const [authed,setAuthed]=useState<boolean|null>(null),[tab,setTab]=useState<Tab>("home");
  useEffect(()=>{api.hasToken().then(setAuthed)},[]);
  useEffect(()=>attachNotificationListeners(data=>{if(data?.screen==="invoices")setTab("invoices");else if(data?.screen==="settings")setTab("settings");else setTab("home")}),[]);
  useEffect(()=>{if(authed)registerPushNotifications()},[authed]);
  if(authed===null)return <Loader/>;
  if(!authed)return <Auth onDone={()=>setAuthed(true)}/>;const screen=tab==="home"?<Home onGoInvoices={()=>setTab("invoices")}/>:tab==="invoices"?<Invoices/>:tab==="add"?<AddInvoice onDone={()=>setTab("invoices")}/>:<Settings onLogout={()=>setAuthed(false)}/>;return <SafeAreaView style={styles.app}><StatusBar style="light"/>{screen}<View style={styles.tabbar}>{(["home","invoices","add","settings"] as Tab[]).map(t=><Pressable key={t} onPress={()=>setTab(t)} style={styles.tab}><Text style={[styles.tabIcon,t===tab&&styles.tabActive]}>{t==="home"?"⌂":t==="invoices"?"▤":t==="add"?"+":"⚙"}</Text><Text style={[styles.tabLabel,t===tab&&styles.tabActive]}>{t==="home"?"Home":t==="invoices"?"Invoices":t==="add"?"Add":"Settings"}</Text></Pressable>)}</View></SafeAreaView>}
const styles=StyleSheet.create({
 app:{flex:1,backgroundColor:colors.bg},screen:{flex:1,backgroundColor:colors.bg},content:{padding:20,paddingBottom:110},
 auth:{flex:1,backgroundColor:colors.bg},center:{flex:1},authScroll:{padding:24,paddingTop:70,paddingBottom:40,minHeight:"100%",justifyContent:"center"},
 brandRow:{flexDirection:"row",alignItems:"center",gap:10},logo:{height:40,width:40,borderRadius:12,backgroundColor:colors.cyan,alignItems:"center",justifyContent:"center"},logoText:{fontSize:22,fontWeight:"900",color:colors.bg},brand:{fontSize:20,fontWeight:"900",color:colors.text},
 kicker:{fontSize:11,fontWeight:"800",letterSpacing:1.5,color:colors.cyan},hero:{fontSize:46,fontWeight:"900",lineHeight:48,color:colors.text,marginTop:14},authSub:{fontSize:16,lineHeight:24,color:colors.muted,marginTop:14,marginBottom:24},
 card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:radius.xl,padding:18},segment:{flexDirection:"row",backgroundColor:colors.surface2,borderRadius:12,padding:4,marginBottom:18},segmentBtn:{flex:1,paddingVertical:10,borderRadius:9,alignItems:"center"},segmentActive:{backgroundColor:colors.white},segmentText:{fontWeight:"800",color:colors.bg},label:{fontSize:12,fontWeight:"700",color:colors.muted,marginBottom:7},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:12,paddingHorizontal:14,color:colors.text,backgroundColor:"#081522"},
 primary:{height:52,borderRadius:14,backgroundColor:colors.white,alignItems:"center",justifyContent:"center",marginTop:6},primaryText:{fontSize:15,fontWeight:"900",color:colors.bg},foot:{fontSize:11,textAlign:"center",color:"#587084",marginTop:18},
 title:{fontSize:30,fontWeight:"900",color:colors.text,marginTop:7},muted:{fontSize:14,lineHeight:21,color:colors.muted,marginTop:5},heroCard:{borderRadius:24,padding:22,marginTop:22,borderWidth:1,borderColor:"#245079"},cardKicker:{fontSize:11,fontWeight:"800",letterSpacing:1.2,color:colors.cyan},money:{fontSize:18,fontWeight:"900",color:colors.text},moneyLarge:{fontSize:34,letterSpacing:-1},heroRow:{flexDirection:"row",justifyContent:"space-between",marginTop:24},smallMuted:{fontSize:11,color:colors.muted,marginBottom:4},whiteBig:{fontSize:20,fontWeight:"900",color:colors.text},statsGrid:{flexDirection:"row",gap:12,marginTop:12},stat:{flex:1,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:16},statLabel:{fontSize:12,color:colors.muted,marginBottom:7},statTone:{fontSize:10,color:"#587084",marginTop:6},actionCard:{marginTop:14,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},actionTitle:{fontSize:15,fontWeight:"900",color:colors.text},arrow:{fontSize:24,color:colors.cyan},invoice:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:16,marginBottom:10},invoiceTop:{flexDirection:"row",alignItems:"center",gap:10},invoiceCustomer:{fontSize:15,fontWeight:"800",color:colors.text},invoiceNo:{fontSize:11,color:colors.muted,marginTop:3},invoiceBottom:{marginTop:14,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},badge:{fontSize:10,fontWeight:"800",color:colors.cyan,backgroundColor:"#123047",paddingHorizontal:9,paddingVertical:6,borderRadius:99},badgeDanger:{color:colors.danger,backgroundColor:"#3A1621"},link:{fontSize:12,fontWeight:"800",color:colors.cyan},empty:{padding:35,alignItems:"center"},emptyTitle:{fontSize:18,fontWeight:"800",color:colors.text,marginBottom:5},settingValue:{fontSize:15,color:colors.text,fontWeight:"700",marginBottom:18},secondaryBtn:{marginTop:14,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface2,borderRadius:14,height:52,alignItems:"center",justifyContent:"center"},secondaryText:{fontWeight:"900",color:colors.cyan},dangerBtn:{marginTop:14,borderWidth:1,borderColor:"#5A2632",backgroundColor:"#2A1119",borderRadius:14,height:52,alignItems:"center",justifyContent:"center"},dangerText:{fontWeight:"900",color:colors.danger},loader:{flex:1,backgroundColor:colors.bg,alignItems:"center",justifyContent:"center",gap:10},tabbar:{position:"absolute",left:12,right:12,bottom:12,height:70,borderRadius:22,backgroundColor:"#0A1625",borderWidth:1,borderColor:colors.line,flexDirection:"row",alignItems:"center",justifyContent:"space-around"},tab:{alignItems:"center",justifyContent:"center",flex:1},tabIcon:{fontSize:19,color:"#587084",fontWeight:"900"},tabLabel:{fontSize:10,color:"#587084",marginTop:2,fontWeight:"700"},tabActive:{color:colors.cyan}
});